### ISSUE TITLE
Cnn model

### ISSUE THREAD

**Issue by DmitryBorin** [yinguobing/cnn-facial-landmark#1]
Hello! 

Great work!
Can you share the pre-train cnn-model for face landmarks detection?

Thanks!

**Comment by yinguobing** [comment]
Hi Dmitry,

Thanks! You can find a pre-trained model [here](https://github.com/yinguobing/head-pose-estimation). It is a exported model file for reference.

**Comment by DmitryBorin** [comment]
Hi!

Thank you for your answer! 
I tried this model, but its quality at large turns does not match what is shown in your second GIF. Could you share a more accurate model? Or maybe you can give some guidance on choosing a method, datasets and other, to get that accuracy?

Thanks!

**Comment by yinguobing** [comment]
Hi Dmitry,

All the gifs comes from the 300-VW dataset, which is used to train the CNN model.
So I guess this might be some kind of over-fitting, as even training samples are randomly chosen from the video frames, still those frames are pretty similar to each other.

You can find out how and why the model was trained in this way from the posts. Sorry they are written in Chinese. Maybe Google translate could help.

**Comment by DmitryBorin** [comment]
Thanks, i'll try to translate your posts. Also, do you have a more accurate model?

**Comment by yinguobing** [comment]
Hi Dmitry,

Sorry this is the best model I have till now. I will update the model file if a better one is available. ☺

**Comment by BenJaminKen** [comment]
您好，我使用你的源码和训练集，把数据做成tfrecord，但是我在训练的时候，提示错误，错误如下：
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 16384 values, but the requested shape has 49152
请问出了什么错误吗？

**Comment by yinguobing** [comment]
建议检查一下输入图像的分辨率以及通道数。

**Comment by humphreyBristol** [comment]
您好，我在用您的源码训练的时候，出现如下错误ValueError: model_fn (<function cnn_model_fn at 0x0000021C84A7B048>) must include features argument. 您的cnn_model_fn第一项不是已经有了Images这个feature了吗，不知道这个错误是因为什么？

**Comment by humphreyBristol** [comment]
@yinguobing 您好，我是用的tensorflow-gpu 1.8的，然后对于您这个程序我改了三个record文件的地址，然后在main函数里面，具体输入的Images是什么类型的量呢，estimator = tf.estimator.Estimator(model_fn=cnn_model_fn
                     , model_dir=r'C:\Users\wangh\Desktop\cnn\record')，程序运行到这边会报错

**Comment by devanandd8245** [comment]
I would like to know the procedures for training "inference_graph.pb" model file so that i could use my dataset's to train and load the model file into the same type of model file to algorithm.

If possible please provide me step by step procedure used for training.

And also i would like to know the kind of annotation of landmark based feature extraction used for the dataset training.

And also the output of the annotated file which is to be provided as input for the training model.

**Comment by devanandd8245** [comment]
I would like to know the CNN training model procedures for obtaining the model file(.pb) step by step

**Comment by AllaaZaki** [comment]
hi.. please what do you mean of (MODEL_PB = 'frozen_graph/frozen_graph.pb')???

**Comment by RamatovInomjon** [comment]
> 您好，我使用你的源码和训练集，把数据做成tfrecord，但是我在训练的时候，提示错误，错误如下：
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 16384 values, but the requested shape has 49152
> 请问出了什么错误吗？

Hi bro, did you find any solution, I got same error, and couldn't start training, please help

**Comment by RamatovInomjon** [comment]
> 建议检查一下输入图像的分辨率以及通道数。

Hi sir, first of all thanks for great job, it is really easy to understand and follow, however I got  "Input to reshape is a tensor with 37632 values, but the requested shape has 49152
" error, please can you explain your answer more clearly, thanks in advance

**Comment by abdou31** [comment]
@RamatovInomjon did you find the solution for the error of input reshape?

**Comment by RamatovInomjon** [comment]
> @RamatovInomjon did you find the solution for the error of input reshape?

Yes, please make sure that dimension of extracted face images and Target_size in the script same , by default they are different (128 and 112)

**Comment by RamatovInomjon** [comment]
@abdou31 Yes, please make sure that dimension of extracted face images and Target_size in the script same , by default they are different (128 and 112)

**Comment by abdou31** [comment]
I have changed this ( if you mean Target_size on pts_tools and extract_face_from_ibug and IMG_WIDTH , IMG_HEIGHT in landmark.py should be the same ) , but i get bad prediction , by default with facial landmark detection i didn't get any error , just with my own dataset i get the error of input reshape
