### ISSUE TITLE
製作tfrecord,產生FileNotFoundError: File b'data/data_train.csv' does not exist

### ISSUE THREAD

**Issue by faust690226** [yinguobing/cnn-facial-landmark#10]
版大請問一下,有兩個問題
(1)用generate_record.sh, 在生成tfrecord時候,會報錯,少了下面三個檔案,是怎麼生成的？
data_train.csv, validation.csv, data_test.csv

(2)此外generate_record.sh的--img_folder=images應該就是放我產生出來的.jpg和.json檔對嘛?

Thanks a lot.

**Comment by yinguobing** [comment]
请参考下这个文件：https://github.com/yinguobing/tfrecord_utility/blob/master/split_data.ipynb

**Comment by yinguobing** [comment]
由于所有的文件都可以从公开渠道获得，所以我没有保存它们。你可以参考下这个文件：https://github.com/yinguobing/tfrecord_utility/blob/a109fe9a2182b5a543835591f3d29b541694a2a1/generate_csv.py
ibug分支也许有你需要的内容。

**Comment by faust690226** [comment]
Hi 版大..
OK...感謝你的資訊~~！
