### ISSUE TITLE
68 landmarks reference

### ISSUE THREAD

**Issue by youjinChung** [yinguobing/cnn-facial-landmark#107]
Hello Yinguobing,

I am trying to merge your repo with my current project.
Since it takes certain points from landmarks, I'd like to know if they match yours.
Do you have any reference documents or pictures for which 68 landmarks this is detecting?

Best,
Youjin

**Comment by yinguobing** [comment]
The demo code used 68 points to be fit with the IBUG datasets. Please note that you can custom the number of points.

IBUG: https://ibug.doc.ic.ac.uk/resources/facial-point-annotations/

**Comment by youjinChung** [comment]
Thank you so much! This confirmed the match!
