### ISSUE TITLE
new Dataset

### ISSUE THREAD

**Issue by liuyuhan1234** [yinguobing/cnn-facial-landmark#108]
How to train this model with the new dataset 300WV?

**Comment by yinguobing** [comment]
Is that a public dataset? Could you post the link here?

**Comment by liuyuhan1234** [comment]
> Is that a public dataset? Could you post the link here?
https://ibug.doc.ic.ac.uk/resources/300-VW/

**Comment by yinguobing** [comment]
You mean 300VW!

That dataset has the exactly same mark format as 300W. Convert the videos into frame images first. The training process is identical to that of the 300W dataset.
