### ISSUE TITLE
300vw.record

### ISSUE THREAD

**Issue by liuyuhan1234** [yinguobing/cnn-facial-landmark#109]
```
 File "/Users/liuyuhan/miniforge3/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Feature: label/marks (data type: string) is required but could not be found.
         [[{{node ParseSingleExample/ParseExample/ParseExampleV2}}]]
         [[IteratorGetNext]] [Op:__inference_train_function_2435]

Function call stack:
train_function
```
When I use this data set, I get the following error

**Comment by yinguobing** [comment]
正如错误信息所述：`label/marks`这个特征没有找到。

建议检查一下tfrecord文件，保证文件中包含该特征。

**Comment by N3UR0NS** [comment]
> tensorflow.python.framework.errors_impl.InvalidArgumentError:  Key: label/marks.  Data types don't match. Data type: float but expected type: string
> 	 [[{{node ParseSingleExample/ParseExample/ParseExampleV2}}]]
> 	 [[IteratorGetNext]] [Op:__inference_train_function_2561]
> 
> Function call stack:
> train_function

same error but it saying datatype mismatch
I've followed all your steps to create tfrecords and checked multiple times the tfrecords files are created perfectly
can you help me with the error
