### ISSUE TITLE
detecting multiple facial landmarks

### ISSUE THREAD

**Issue by lalapo** [yinguobing/cnn-facial-landmark#16]
can we implement your model for recognizing multiple facial landmarks?

**Comment by yinguobing** [comment]
By "multiple facial landmarks", you mean landmarks of multiple people, right?

The most obvious way is for each of the faces you found in a image, use a individual detector. However, if you want to output all landmarks with a single detector, the best way might be using similar procedure reported in this paper: 
https://github.com/CMU-Perceptual-Computing-Lab/openpose

**Comment by yinguobing** [comment]
By "multiple facial landmarks", you mean landmarks of multiple people, right?

The most obvious way is for each of the faces you found in a image, use a individual detector. However, if you want to output all landmarks with a single detector, the best way might be using similar procedure reported in this paper: 
https://github.com/CMU-Perceptual-Computing-Lab/openpose

**Comment by lalapo** [comment]
thank you so much for your reply,  I hope you can make the tutorial for open pose :)
by the way,  I am really satisfied about your facial landmark tutorial, because your tutorial is briefly and clearly explained. feeling so grateful knowing this post

**Comment by yinguobing** [comment]
Glad you like it~ :smiley:
