### ISSUE TITLE
freeze_graph时Output找不到问题

### ISSUE THREAD

**Issue by henrypig** [yinguobing/cnn-facial-landmark#17]
File "/home/linxiongcai/tensorflow-new/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/util/deprecation.py", line 318, in new_func
    return func(*args, **kwargs)
  File "/home/linxiongcai/tensorflow-new/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/framework/graph_util_impl.py", line 245, in convert_variables_to_constants
    inference_graph = extract_sub_graph(input_graph_def, output_node_names)
  File "/home/linxiongcai/tensorflow-new/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/util/deprecation.py", line 318, in new_func
    return func(*args, **kwargs)
  File "/home/linxiongcai/tensorflow-new/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/framework/graph_util_impl.py", line 181, in extract_sub_graph
    _assert_nodes_are_present(name_to_node, dest_nodes)
  File "/home/linxiongcai/tensorflow-new/tensorflow/bazel-bin/tensorflow/python/tools/freeze_graph.runfiles/org_tensorflow/tensorflow/python/framework/graph_util_impl.py", line 137, in _assert_nodes_are_present
    assert d in name_to_node, "%s is not in graph" % d
AssertionError: logits/BiasAdd:0 is not in graph

freeze_graph代码：
bazel-bin/tensorflow/python/tools/freeze_graph\
    --input_saved_model_dir=/home/facial_landmark/cnn-facial-landmark/cnn-facial-landmark-save_model/saved_model/1553825325 \
    --output_graph=/home/facial_landmark/cnn-facial-landmark/cnn-facial-landmark-save_model/saved_model/1553825325/frozen.pb \
    --output_node_names='logits/BiasAdd:0'

**Comment by henrypig** [comment]
请问这个问题要怎么解决，偿试过以下node name都失败了
output_node_names='logits/BiasAdd:0'
output_node_names='logits‘
output_node_names='marks‘

**Comment by yinguobing** [comment]
如果是node的问题，尝试把graph里的所有node name都打印出来检查下吧。

**Comment by henrypig** [comment]
python3 ./tensorflow/python/tools/inspect_checkpoint.py --file_name=/home/facial_landmark/cnn-facial-landmark/train/model.ckpt-363517

graph的Node是这样的：
beta1_power (DT_FLOAT) []
beta2_power (DT_FLOAT) []
conv2d/bias (DT_FLOAT) [32]
conv2d/bias/Adam (DT_FLOAT) [32]
conv2d/bias/Adam_1 (DT_FLOAT) [32]
conv2d/kernel (DT_FLOAT) [3,3,3,32]
conv2d/kernel/Adam (DT_FLOAT) [3,3,3,32]
conv2d/kernel/Adam_1 (DT_FLOAT) [3,3,3,32]
conv2d_1/bias (DT_FLOAT) [64]
conv2d_1/bias/Adam (DT_FLOAT) [64]
conv2d_1/bias/Adam_1 (DT_FLOAT) [64]
conv2d_1/kernel (DT_FLOAT) [3,3,32,64]
conv2d_1/kernel/Adam (DT_FLOAT) [3,3,32,64]
conv2d_1/kernel/Adam_1 (DT_FLOAT) [3,3,32,64]
conv2d_2/bias (DT_FLOAT) [64]
conv2d_2/bias/Adam (DT_FLOAT) [64]
conv2d_2/bias/Adam_1 (DT_FLOAT) [64]
conv2d_2/kernel (DT_FLOAT) [3,3,64,64]
conv2d_2/kernel/Adam (DT_FLOAT) [3,3,64,64]
conv2d_2/kernel/Adam_1 (DT_FLOAT) [3,3,64,64]
conv2d_3/bias (DT_FLOAT) [64]
conv2d_3/bias/Adam (DT_FLOAT) [64]
conv2d_3/bias/Adam_1 (DT_FLOAT) [64]
conv2d_3/kernel (DT_FLOAT) [3,3,64,64]
conv2d_3/kernel/Adam (DT_FLOAT) [3,3,64,64]
conv2d_3/kernel/Adam_1 (DT_FLOAT) [3,3,64,64]
conv2d_4/bias (DT_FLOAT) [64]
conv2d_4/bias/Adam (DT_FLOAT) [64]
conv2d_4/bias/Adam_1 (DT_FLOAT) [64]
conv2d_4/kernel (DT_FLOAT) [3,3,64,64]
conv2d_4/kernel/Adam (DT_FLOAT) [3,3,64,64]
conv2d_4/kernel/Adam_1 (DT_FLOAT) [3,3,64,64]
conv2d_5/bias (DT_FLOAT) [128]
conv2d_5/bias/Adam (DT_FLOAT) [128]
conv2d_5/bias/Adam_1 (DT_FLOAT) [128]
conv2d_5/kernel (DT_FLOAT) [3,3,64,128]
conv2d_5/kernel/Adam (DT_FLOAT) [3,3,64,128]
conv2d_5/kernel/Adam_1 (DT_FLOAT) [3,3,64,128]
conv2d_6/bias (DT_FLOAT) [128]
conv2d_6/bias/Adam (DT_FLOAT) [128]
conv2d_6/bias/Adam_1 (DT_FLOAT) [128]
conv2d_6/kernel (DT_FLOAT) [3,3,128,128]
conv2d_6/kernel/Adam (DT_FLOAT) [3,3,128,128]
conv2d_6/kernel/Adam_1 (DT_FLOAT) [3,3,128,128]
conv2d_7/bias (DT_FLOAT) [256]
conv2d_7/bias/Adam (DT_FLOAT) [256]
conv2d_7/bias/Adam_1 (DT_FLOAT) [256]
conv2d_7/kernel (DT_FLOAT) [3,3,128,256]
conv2d_7/kernel/Adam (DT_FLOAT) [3,3,128,256]
conv2d_7/kernel/Adam_1 (DT_FLOAT) [3,3,128,256]
dense/bias (DT_FLOAT) [1024]
dense/bias/Adam (DT_FLOAT) [1024]
dense/bias/Adam_1 (DT_FLOAT) [1024]
dense/kernel (DT_FLOAT) [6400,1024]
dense/kernel/Adam (DT_FLOAT) [6400,1024]
dense/kernel/Adam_1 (DT_FLOAT) [6400,1024]
global_step (DT_INT64) []
logits/bias (DT_FLOAT) [136]
logits/bias/Adam (DT_FLOAT) [136]
logits/bias/Adam_1 (DT_FLOAT) [136]
logits/kernel (DT_FLOAT) [1024,136]
logits/kernel/Adam (DT_FLOAT) [1024,136]
logits/kernel/Adam_1 (DT_FLOAT) [1024,136]

**Comment by henrypig** [comment]
export_savedmodel时定义的export_outputs不在这里

**Comment by yinguobing** [comment]
请问您的TensorFlow版本是？看起来是比较新的版本。

**Comment by yinguobing** [comment]
另外save model的时候可参考下`save_model`分支，使用estimator将模型导出。

**Comment by henrypig** [comment]
Tensorflow版本是1.9；用于freeze的pb文件就是用您save_model分支生成的。

**Comment by henrypig** [comment]
train 用到的Tensorflow版本是1.9，是直接安装的。但freeze_graph文件是下载2.0源码里的。会不会是这两个版本不一样导致的？

**Comment by yinguobing** [comment]
我不确定，试一下吧。

**Comment by henrypig** [comment]
已经解决了，用/usr/local/lib/python3.5/dist-packages/tensorflow/python/tools里的freeze_graph就可以，感谢。

**Comment by AllaaZaki** [comment]
> 已经解决了，用/usr/local/lib/python3.5/dist-packages/tensorflow/python/tools里的freeze_graph就可以，感谢。
please can you share how you generate the frozen.pb step by step  
please

**Comment by freedanfan** [comment]
我训练出的模型为：
model.ckpt-200000.meta  
model.ckpt-200000.index 
model.ckpt-200000.data-00000-of-00001

使用 tensorflow的freeze_graph生成pd文件的代码如下：
----------------------------------------------------------------------------------------------
from tensorflow.python.tools import freeze_graph

input_meta_graph = "./model/model.ckpt-200000.meta"
checkpoint = './model/model.ckpt-200000'
output_graph_filename ='./model/freeze_model/output_graph.pb'

input_saver_def_path = ""
input_binary = True
output_node_names = 'logits/kernel/Adam_1'
restore_op_name = "save/restore_all"
filename_tensor_name = "save/Const:0"
clear_devices = False

freeze_graph.freeze_graph(
    "", input_saver_def_path, input_binary, checkpoint,
    output_node_names, restore_op_name, filename_tensor_name,
    output_graph_filename, clear_devices, "", "", "", input_meta_graph)
----------------------------------------------------------------------------------------------
为什么我生成的pd文件只有571Kb?

**Comment by yinguobing** [comment]
@freedanfan 
我并未直接import `freeze_graph.py` module，而是使用 `python3 freeze_graph.py` 的方式。文件小可能是冻结的网络不全？

鉴于作者issue已解决，如果有问题欢迎开新issue。

**Comment by abdou31** [comment]
@freedanfan did you solved the problem?
