### ISSUE TITLE
pb转coreml遇到的问题

### ISSUE THREAD

**Issue by yiyoyiyo** [yinguobing/cnn-facial-landmark#18]
pb文件转coreml遇到这个error：
ValueError: Input 0 of node Reshape was passed float from input_image_tensor:0 incompatible with expected uint8.
看楼主博文提到这个问题需要指定输入tensor的第一个维度为1；请问下这个是要freeze graph的时候做还是在到处saved_model时候做
谢谢

**Comment by yinguobing** [comment]
我记得是在save model的时候完成的。

**Comment by xiaojunxuhaha** [comment]
问一下 那个face_detector能再发一次吗 那个连接失效了 谢谢
