### ISSUE TITLE
data.csv的内容是什么？

### ISSUE THREAD

**Issue by LingQiu** [yinguobing/cnn-facial-landmark#2]
您好，请问data.csv的内容是什么格式的？是不是有3列内容，第一列是图片的路径，第二列是对应图片标注的68个点的横坐标，第三列是相应的68个点的纵坐标。
谢谢

**Comment by yinguobing** [comment]
抱歉文件太多了，你说的这个文件在哪里呀？

**Comment by LingQiu** [comment]
您好，我往这个邮箱yinguobing@gmail.com发了邮件，还请指教。

**Comment by yinguobing** [comment]
LingQiu 你好！

时间久远，我没有保存相关的文件。

从`generate_csv.py`里的`writeheader()`函数来看，这个CSV文件包含的应该是图片文件与json文件的路径。

**Comment by LingQiu** [comment]
好的，谢谢
