### ISSUE TITLE
CNN model for facial landmark 

### ISSUE THREAD

**Issue by ZlaaM** [yinguobing/cnn-facial-landmark#20]
I would like to know the facial landmark CNN training model procedures for obtaining the model file(frozen.pb) step by step

 

please help me

**Comment by yinguobing** [comment]
@AllaaZaki 
The TensorFlow team had provided a detailed explanation of how to freeze a model in this file:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py

You may start by reading this line:
https://github.com/tensorflow/tensorflow/blob/6f8ffb95f89296ff9accd7717f825547351ddd8a/tensorflow/python/tools/freeze_graph.py#L302

**Comment by Msj5** [comment]
Hi,can you show me the "output_node_names" in your network? Thanks@yinguobing
