### ISSUE TITLE
extract face from ibug

### ISSUE THREAD

**Issue by xiaojunxuhaha** [yinguobing/cnn-facial-landmark#24]
请问extract face from ibug跑通了但是生成的图片并没有关键点 是为什么呢 我的pts_tool文件的结果是所有图片扫描后就没有了，结果如下
Fitting failed!
Using minimal box.
opps! 394 566
我的extract face from ibug结果如下
New file saved:
C:/Users/Xuxiaojun/PycharmProjects/untitled15/223k/300vw\300vw-dataset-image_99.jpg
C:/Users/Xuxiaojun/PycharmProjects/untitled15/223k/300vw\300vw-dataset-image_99.json
All done! Total file: 135, invalid: 0, succeed: 135

Process finished with exit code 0
图片上没有关键点。
pts的data_dir DATA_DIR = "C:/Users/Xuxiaojun/PycharmProjects/untitled15/dataset/ibug"
extract face from ibug的DATA_DIR = "C:/Users/Xuxiaojun/PycharmProjects/untitled15/dataset/ibug"
两者是否需要保持一致呢？我看作者的pts的dir只是写到了dataset，并没有具体到那个数据集 但是我的不具体就会报错 而且写其他的数据集也会报错 请问一下为什么呢。麻烦大家了

**Comment by yinguobing** [comment]
图片上没有关键点的意思是？

**Comment by xiaojunxuhaha** [comment]
您好 就是我看有人发的问题回答里，跑完 extract face from ibug后会显示关键点 我的没有 。而且检测人脸的时候我的图片显示白色的框比绿色的框小 而您的是白色框包含了绿色的。因为刚刚接触 不熟悉 给你添麻烦了 抱歉




------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>;
发送时间: 2019年4月26日(星期五) 下午3:21
收件人: "yinguobing/cnn-facial-landmark"<cnn-facial-landmark@noreply.github.com>;
抄送: "许晓君"<2314232838@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [yinguobing/cnn-facial-landmark] extract face from ibug (#24)




图片上没有关键点的意思是？

**Comment by yinguobing** [comment]
是否方便提供下你看到的相关描述的具体地址？

**Comment by xiaojunxuhaha** [comment]
就是这个问题底下某位的回答


------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>;
发送时间: 2019年4月26日(星期五) 下午3:33
收件人: "yinguobing/cnn-facial-landmark"<cnn-facial-landmark@noreply.github.com>;
抄送: "许晓君"<2314232838@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [yinguobing/cnn-facial-landmark] extract face from ibug (#24)




是否方便提供下你看到的相关描述的具体地址？

**Comment by yinguobing** [comment]
issue #24 吗？目前好像没有其他人的回复。

**Comment by xiaojunxuhaha** [comment]
是的 但是提问人应该自己解决了




------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>;
发送时间: 2019年4月26日(星期五) 下午3:42
收件人: "yinguobing/cnn-facial-landmark"<cnn-facial-landmark@noreply.github.com>;
抄送: "许晓君"<2314232838@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [yinguobing/cnn-facial-landmark] extract face from ibug (#24)




issue #24 吗？目前好像没有其他人的回复。
