### ISSUE TITLE
landmark

### ISSUE THREAD

**Issue by ZlaaM** [yinguobing/cnn-facial-landmark#29]
Are you working on updating it ?

**Comment by yinguobing** [comment]
I'm trying. :coffee:

**Comment by ZlaaM** [comment]
in which version of tensorflow  have you written this code ?

**Comment by yinguobing** [comment]
1.4

**Comment by ZlaaM** [comment]
please can you share your " frozon_graph.pb " or the name of the output nodes ?
because i still have this problem (
KeyError: "The name 'logits/BiasAdd:0' refers to a Tensor which does not exist. The operation, 'logits/BiasAdd', does not exist in the graph." ) 
thanks alot

**Comment by yinguobing** [comment]
May I ask which version of TensorFlow are you using?
It might be Duplicate of #17

**Comment by ZlaaM** [comment]
i try tf1.13 , 1.9 and 1.2

**Comment by ZlaaM** [comment]
and 1.4

**Comment by ZlaaM** [comment]
I tried the same (#17) but the problem still exists

**Comment by ZlaaM** [comment]
thank you for your interest .. i solved it

**Comment by yinguobing** [comment]
Glad to hear that :smiley: , safe to close #29.
