### ISSUE TITLE
demo中的关键点还是在抖动

### ISSUE THREAD

**Issue by ailias** [yinguobing/cnn-facial-landmark#3]
感觉示例中的关键点还是在抖动呢。有没有好的解决办法呢？

**Comment by yinguobing** [comment]
是的，这个问题并没有彻底解决。我建议参考下OpenFACE。

**Comment by yinguobing** [comment]
也可以考虑下NMS.

**Comment by ailias** [comment]
OpenFace确实可以减少抖动，但是还是没有彻底解决抖动问题。而且因为它加了跟踪，所以在准确度上会下降，例如人脸的快速移动场景会导致关键点跟踪滞后问题。
个人感觉应该是怎样让跟踪和检测有个更好的协作关系来解决抖动问题。例如，当判断两帧是小范围运动时则使用跟踪；大范围则重新启动检测。所以这个判断条件就很重要了。

**Comment by yinguobing** [comment]
建议试一下NMS。

**Comment by zxt881108** [comment]
@yinguobing 请问这个NMS是指哪篇论文？

**Comment by yinguobing** [comment]
@zxt881108 none max suppression.
