### ISSUE TITLE
Training with own dataset

### ISSUE THREAD

**Issue by abdou31** [yinguobing/cnn-facial-landmark#35]
Hello Sir,
Did you can explain with details how to train own dataset ( custom dataset ) to detect custom object for exemple , I need to training my dataset to detect the region of iris in the eye , 
So i need to add keypoints for the iris region 
Thanks

**Comment by yinguobing** [comment]
I think this could be classified as an object detection, or an image segmentation problem. Whichever case it is, direct regression of "iris region" may not be the best option.

You can replace the training file and modify the last layer of the network to match your custom data, if you still want to try,

**Comment by abdou31** [comment]
Did you mean that it is impossible or hard to detect the iris in real time with you tool ( project ) ?
exemple for that i want :
![image](https://user-images.githubusercontent.com/19480228/57440944-3c381c00-7249-11e9-9f67-c5b3e61d6e70.png)

**Comment by yinguobing** [comment]
I think it's possible, from the image you posted.
Give it a try. :smile:

**Comment by abdou31** [comment]
Thanks , 
I have some issues , can i open new issue or continues the discussion here?

**Comment by yinguobing** [comment]
One thread one issue please.
It would be more clear and easy to be find for later users with similar issues.

**Comment by abdou31** [comment]
Okey we continue here ,
So i have cloned your project and i have installed the req packages ( tensorflow and opencv) i don't know the project work with cpu or gpu , so after installing those packages i run 

> python landmark.py 

 i get error :

>python stopped working

I installed after that tensorflow-gpu and i run again the command , i get this error:

![image](https://user-images.githubusercontent.com/19480228/57443694-f3836180-724e-11e9-9a04-369c5b40b39c.png)

How can i solve those errors?

**Comment by yinguobing** [comment]
Both CPU & GPU TensorFlow are fine. Choose GPU version if you have a CUDA capable GPU. 
It looks like your TensorFlow installation is not working. Try this in your terminal:

`python3 -c "import tensorflow as tf; print(tf.__version__)"
`

There should be no error message but only the TensorFlow version in the output.

By the way, all these issues is related to your project, but they are different issues. So please open new one next time, thanks.

**Comment by abdou31** [comment]
When i execute this command i get the error mentionned in the image that i set : 
![image](https://user-images.githubusercontent.com/19480228/57446714-a787eb00-7255-11e9-8ec4-06521f463a16.png)

**Comment by yinguobing** [comment]
Error occurred when importing TensorFlow. It should be a TensorFlow installation problem.
Are you using Winodws?

**Comment by abdou31** [comment]
yes i use :

+ Windows 10 x64
+ cudnn 7.5
+ Cuda 10.0
+ Tenserflow-gpu 1.13
+ Nvidia Geforce 840m ( Graphic card )

**Comment by yinguobing** [comment]
I recommend re-installing TensorFlow following the official installation instructions.

**Comment by abdou31** [comment]
Thanks Sir , problem solved after following the official installation instructions
