### ISSUE TITLE
Error when execute extract_face_from_ibug.py

### ISSUE THREAD

**Issue by abdou31** [yinguobing/cnn-facial-landmark#39]
Hello , 
I have organize my data , but when i execute extract_face_from_ibug.py i get this error :

> python extract_face_from_ibug.py 

> PTS file numbers: 218597
  0%|                                                                   | 0/218597 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "extract_face_from_ibug.py", line 143, in <module>
    main()
  File "extract_face_from_ibug.py", line 115, in main
    subset_name = head.split('/')[-2]
IndexError: list index out of range

How can i solve it ?
Thanks

**Comment by abdou31** [comment]
This error is from windows os , If anyone get this problem , 
he should change
`subset_name= head.split('/')[-2]`

by 

`subset_name = head.split(os.path.sep)[-2]`

**Comment by yinguobing** [comment]
@abdou31 
Glad you figure it out. I was developing in Linux and had not noticed that Windows is using a different way to separate directories. You can make a pull request to fix this permanently.

**Comment by abdou31** [comment]
In order to give everyone their right , I really solved the error by asking a question in stackoverflow and someone gave me the solution :
https://stackoverflow.com/questions/56166760/subset-name-head-split-2-indexerror-list-index-out-of-range/56167136#56167136
