### ISSUE TITLE
reshape错误

### ISSUE THREAD

**Issue by BenJaminKen** [yinguobing/cnn-facial-landmark#4]
您好，我使用你的源码和训练集，把数据做成tfrecord，但是我在训练的时候，提示错误，错误如下： tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to  reshape is a tensor with 16384 values, but the requested shape has 49152 请问出了什么错误吗？
--

**Comment by yinguobing** [comment]
Hi Ben,

49152 = 128 * 128 * 3
16384 = 128 * 128
看上去，你似乎使用了单通道图像。

**Comment by BenJaminKen** [comment]
但是我使用的是你给的数据集，都是rgb的，我也通过程序遍历了一遍，都是3通道的

**Comment by BenJaminKen** [comment]
首先剔除一些不好的数据，然后生成csv，在生成tfrecord.最后拿来训练，然后就出现这个错误了

**Comment by BenJaminKen** [comment]
使用的是你的这个脚本生成的tfrecord

**Comment by BenJaminKen** [comment]
https://github.com/yinguobing/tfrecord_utility/blob/master/generate_tfrecord.py生成tfrecord文件的脚本

**Comment by BenJaminKen** [comment]
https://github.com/yinguobing/tfrecord_utility/blob/master/generate_tfrecord.py生成tfrecord脚本，这个是生成

**Comment by yinguobing** [comment]
是否方便提供一份有问题的tfrecord文件？

**Comment by BenJaminKen** [comment]
链接：https://pan.baidu.com/s/10La38sBHgpox8mZ22qMa_A 密码：7j8x

**Comment by BenJaminKen** [comment]
您好，这个问题我解决了，把这两句代码

**Comment by BenJaminKen** [comment]
但是又出现了另外一个问题  训练一会就出现下面的问题

**Comment by BenJaminKen** [comment]
有一个疑惑，您为什么将特征点的位置归一化呢，这样的话，在卷积的时候，特征点的位置不是对应不上图片的位置了吗？

**Comment by BenJaminKen** [comment]
请问导出pb模型的--output_node_names参数是什么？

**Comment by BenJaminKen** [comment]
请问“分析神经网络在实战图像中产生较大偏差的原因，并尝试提出可能的解决方法”，这篇文章有发布吗

**Comment by yinguobing** [comment]
没有。我一直没有找到好的办法去验证自己的猜想。

**Comment by BenJaminKen** [comment]
您好，请问检测特征点张嘴的时候，我这边的所有特征点都往下移动了，你那边会这样吗

**Comment by Chromer163** [comment]
你好，我有一个猜想就是，你在做人脸对齐的时候，训练样本最好先摆正，在送入网络做训练比较好。

**Comment by Chromer163** [comment]
另外，请问你坐标变换那一部分代码在哪里提供的呢？

**Comment by yinguobing** [comment]
@BenJaminKen 你可以参考下https://github.com/yinguobing/head-pose-estimation，你看到的结果就是我这里的结果。

**Comment by yinguobing** [comment]
@Chromer163 视你的使用策略，可以这样做。
另外建议一个主题一个issue，以方便后来者查阅。

**Comment by daiqiuli** [comment]
你好，我也出现了tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 16384 values, but the requested shape has 49152错误，不知道怎么解决
