### ISSUE TITLE
False results with landmark.py 

### ISSUE THREAD

**Issue by abdou31** [yinguobing/cnn-facial-landmark#41]
Hello , 
I have executed landmark.py , but i get false results of prediction , 
Do you know the reason?
![image](https://user-images.githubusercontent.com/19480228/57930044-3da2bd80-78b5-11e9-8019-0638719d3467.png)

**Comment by ZlaaM** [comment]
this result is before training the model

**Comment by abdou31** [comment]
yes , for the first time i think that give result without training with pre trained model , i didn't know actually how to use pre trained model correctly
