### ISSUE TITLE
prediction wih 3D 

### ISSUE THREAD

**Issue by abdou31** [yinguobing/cnn-facial-landmark#42]
Hello , 
I want to know how can i use 3D in the model to get good values?

**Comment by yinguobing** [comment]
Could you be more specific about this question?

**Comment by abdou31** [comment]
After training and reached the 92104 steps , i get good resultat for face landmark for frontal face ,
but no good for profil view ( false result ) 
Like this : ( see the right gif ) 
https://github.com/yinguobing/cnn-facial-landmark/blob/master/demo02.gif

**Comment by yinguobing** [comment]
The demo gifs are actually extracted from the 300VW dataset, which have been used in the training process. This makes them not suitable for evaluating the model's performance.

Since you have successfully trained a model, I think it's a good time for you to read this paper:
https://arxiv.org/abs/1608.04188

**Comment by abdou31** [comment]
Okey Thanks , 
Do you have idea how can i train my own dataset? 
You know that i want to detect iris region ( in the eye ) using landmarks detection, i want to use dataset landmarks that gives iris landmarks , if doese not exist , i want to know how can i annotate dataset with landmarks to get specifics anootations for own dataset?

**Comment by yinguobing** [comment]
Try this one: https://www.menpo.org/landmarkerio/

**Comment by abdou31** [comment]
The tool that you post doesn't work for me , I installed this tool :
+ https://github.com/luigivieira/Facial-Landmarks-Annotation-Tool
it works fine ,I tried to annotating face data with iris landmarks ( iris in the eye )
I want to know the number of points that CNN-facial landmarks accept for training and for testing .
For exemple in this picture , i have 10 points : ( 5 for right iris and 5 for left iris )
![annot](https://user-images.githubusercontent.com/19480228/58388080-069d7c00-801a-11e9-9072-ae7833d9be80.PNG)

What is the maximal number of landmarks that can i using for annotation iris region?

**Comment by abdou31** [comment]
My question is about 3D , If i have values for exemple in .pts file : ( simple file containes x and y coordinates )

>n_points 68 {
>252.23 415.1 
>...
>}
If i have the other coordinate z that used for 3D , is it possible to detect the landmarks facial in 3D ( x,y,z)?
+ I mean when the head make a rotate , the landmarks should follow the face.

**Comment by yinguobing** [comment]
I think it is possible if you have 3D points as training data.

**Comment by abdou31** [comment]
Did the project can train z coordinate? ( 3D annotation )
if yes what can be the form of pts file and what should I modified in scripts of images utility?
