### ISSUE TITLE
Using summary to vizualize the graph

### ISSUE THREAD

**Issue by abdou31** [yinguobing/cnn-facial-landmark#45]
Hello ,
I want to vizuale the model graph using summaries , for exemple every 1000 steps 
How to do that ? is it possible using this by modifying code in landmark.py
Thanks

**Comment by yinguobing** [comment]
Tensorboard could do that.

**Comment by abdou31** [comment]
Thanks, 
i have not fixed the problem of graph that increase , you say in the post of deep learning history that you solve the problem , i will try to understand what you do to solve the problem of training

**Comment by yinguobing** [comment]
This issue should be resolved in the latest commit.
