### ISSUE TITLE
Number of points for annotation 

### ISSUE THREAD

**Issue by abdou31** [yinguobing/cnn-facial-landmark#46]
Hello ,
I want to know is there a relationship between the number of points and the convolutional neural network?
what can be the number of points that CNN-facial landmarks accept for training and for testing .
For exemple in this picture , i have 10 points : ( 5 for right iris and 5 for left iris )
![image](https://user-images.githubusercontent.com/19480228/58524265-f1fee680-81c7-11e9-8dea-ea7c8e17dae6.png)
What is the maximal number of landmarks that can i using for annotation iris region?
is it depends on you tool or on the convolutional neural network created?
Thanks

**Comment by yinguobing** [comment]
I think the number of points depends on the definition of your problem to be solved. In general, less points require less model parameters, and yes, it's not related with this tool.

**Comment by abdou31** [comment]
Thanks @yinguobing
