### ISSUE TITLE
Detect from webcam CNN Facial landmarks

### ISSUE THREAD

**Issue by abdou31** [yinguobing/cnn-facial-landmark#51]
Hello, 
I know that this issue is duplicated https://github.com/yinguobing/cnn-facial-landmark/issues/47 ,
but the repo of head pose estimation project doesn't help me and I did not find the best way to detect face from Webcam if you can please give me some instructions and thanks

**Comment by yinguobing** [comment]
OpenCV's DNN module had provided some great samples, including face detection.
https://github.com/opencv/opencv/tree/master/samples/dnn

**Comment by abdou31** [comment]
I have two questions:
1/ This is DNN and the project is based on CNN, is it normal?
2/ This project use caffemodel, it can use other models like ( ResNet )?

**Comment by yinguobing** [comment]
Q1. It is.
Q2. Yes.

**Comment by abdou31** [comment]
Thanks.
