### ISSUE TITLE
 Filling up shuffle buffer (this may take a while)

### ISSUE THREAD

**Issue by abdou31** [yinguobing/cnn-facial-landmark#52]
I trained my own dataset using CNN facial landmarks, 
I get these lines during the training, what does meaning?
> 2019-06-19 11:51:47.300554: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:101] Filling up shuffle buffer (this may take a while): 7138 of 10000
2019-06-19 11:51:51.690415: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:140] Shuffle buffer filled.

Can it decrease the prediction's performance?

**Comment by yinguobing** [comment]
I don't think so.

**Comment by abdou31** [comment]
Please try to answer me on others question.
Thanks
