### ISSUE TITLE
Saving model failed during training

### ISSUE THREAD

**Issue by wangping1408** [yinguobing/cnn-facial-landmark#59]
I used your newly uploaded landmark.py file, but there was such an error during training. I would like to ask if you can help me.
![Screenshot from 2019-07-09 09-26-41](https://user-images.githubusercontent.com/43232577/60852871-2be1f480-a22c-11e9-880d-7dcc96c5767c.png)

**Comment by yinguobing** [comment]
and the error message is?

**Comment by wangping1408** [comment]
Is my problem, I know the cause of the problem, thank you

**Comment by yinguobing** [comment]
Safe to close #59
