### ISSUE TITLE
开始训练以后出现问题

### ISSUE THREAD

**Issue by bobbySpace** [yinguobing/cnn-facial-landmark#6]
使用landmark.py开始训练
训练100步以后提示
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 1 into ./train/model.ckpt.
INFO:tensorflow:loss = 11.351076, step = 1
INFO:tensorflow:global_step/sec: 0.848605
INFO:tensorflow:loss = 0.0079134945, step = 101 (117.843 sec)
INFO:tensorflow:Saving checkpoints for 200 into ./train/model.ckpt.
INFO:tensorflow:Loss for final step: 0.0037037705.
INFO:tensorflow:Calling model_fn.

model_fn_results = self._model_fn(features=features, **kwargs)
  File "landmark.py", line 27, in cnn_model_fn
    inputs = tf.to_float(features['x'], name="input_to_float")
KeyError: 'x'

**Comment by bobbySpace** [comment]
找到问题了，之前切换到save model那个分支，后来改回主分支以后改了一下代码导致。。。
已经解决，非常感谢～～～

**Comment by yinguobing** [comment]
应该感谢你自己，我都不知道问题出在哪里。

**Comment by bobbySpace** [comment]
我当时这个问题产生的原因是我把分支切换到了save model，然后进行训练导致。把分支切换到master，再进行训练就没问题了。

**Comment by UestcZbq** [comment]
> 我当时这个问题产生的原因是我把分支切换到了save model，然后进行训练导致。把分支切换到master，再进行训练就没问题了。

我是使用的master分支里面landmark，但是仍然报这个错误，能帮忙解决一下吗？

**Comment by UestcZbq** [comment]
> 应该感谢你自己，我都不知道问题出在哪里。

Hi，这个KeyError: 'x'问题感觉大家都普遍存在，能统一帮助大家解决一下吗？谢谢您
