### ISSUE TITLE
方便提供训练的数据集吗

### ISSUE THREAD

**Issue by Germey** [yinguobing/cnn-facial-landmark#7]
读了您的博文，收获很大，非常感谢您的工作！
请问您方便分享一下您处理之后的数据集吗？即每张图片和对应Landmark的数据集，盼复。

**Comment by yinguobing** [comment]
Hi Germey，由于所有数据都可以公开获得，生成数据的方式已经写在博客里，并把代码推到了Github，所以没有保留处理之后的数据。你可以尝试自己生成一份。

**Comment by qiaowei1214** [comment]
300vw，300w官网下载的都解压失败。。。
