### ISSUE TITLE
画图工具

### ISSUE THREAD

**Issue by genty1314** [yinguobing/cnn-facial-landmark#75]
您好，我拜读您的博客--可深度分离卷积（链接：https://yinguobing.com/separable-convolution/#fn2），博客写的清晰明了，非常感谢。我发现您博客中的插图（解析卷积操作的）非常精细，请问是用何种工具，方便告诉下面。

**Comment by yinguobing** [comment]
Hi genty1314，我用的是PowerPoint。

genty1314 <notifications@github.com>于2019年9月17日 周二下午9:03写道：

**Comment by genty1314** [comment]
非常感谢。

**Comment by genty1314** [comment]
已解决
