### ISSUE TITLE
请问，引用的是face++哪一篇论文呢？

### ISSUE THREAD

**Issue by patrickwf** [yinguobing/cnn-facial-landmark#8]
如题，谢谢~

**Comment by yinguobing** [comment]
Approaching Human Level Facial Landmark Localization by Deep Learning

**Comment by yinguobing** [comment]
很难说。卡在某局部最优？试试从头开始训练。

**Comment by yinguobing** [comment]
Closed as the issue seems to be resolved.

**Comment by ZhangYuef** [comment]
> Approaching Human Level Facial Landmark Localization by Deep Learning

您好，似乎您的代码只实现了原论文两阶段人脸特征点检测中的第一阶段？

**Comment by yinguobing** [comment]
@zhangyuf
 
是的。请留意最新的代码在原有基础上做了更多的改动，不能完全匹配论文中的结构。

**Comment by ZhangYuef** [comment]
> @zhangyuf
> 
> 是的。请留意最新的代码在原有基础上做了更多的改动，不能完全匹配论文中的结构。

@yinguobing 请问这些改动的原因是什么呢？是发现改动过后实验效果更好么？

**Comment by yinguobing** [comment]
效果是一方面，另一方面网络收敛更快，方便新手训练调试。
