### ISSUE TITLE
請問一下, 運用PTS_Tool.py來畫出68個特徵點在圖片上出現問題

### ISSUE THREAD

**Issue by faust690226** [yinguobing/cnn-facial-landmark#9]
https://yinguobing.com/facial-landmark-localization-by-deep-learning-data-collate/
根據你這篇博文的說明,下載了pts_tool.py和face_detector.py等程式碼,執行會發生下面錯誤dnn 的fail,查了之後感覺好像是cudnn沒install, 但我已經安裝了... 不知道是何原因? 因為cv2無法run在python3之上, 所以我是用 Anaconda run Python 3.6.5解決這問題,接著就遇到dnn 錯誤的問題

fail log:
(cv3) faust@faust-GX501VIK:~/LinuxCode/image_utility$ python3.6 pts_tools.py
Traceback (most recent call last):
  File "pts_tools.py", line 8, in <module>
    import face_detector as fd
  File "/home/faust/LinuxCode/image_utility/face_detector.py", line 7, in <module>
    from cv2 import dnn
ImportError: cannot import name 'dnn'

**Comment by yinguobing** [comment]
看起來像是OpenCV版本問題。OpenCV的`dnn`模塊只在較新版本中提供。建議您檢查一下所安裝OpenCV的版本號。我所使用的3.4.2驗證通過。

**Comment by faust690226** [comment]
感謝版大...這問題解決,
但又出現找不到檔案的fail log
查了一下,face_detector在opencv的source code有
但裡面沒有res10_300x300_ssd_iter_140000.caffemodel這檔案

PROTOTXT = 'face_detector/deploy.prototxt'
MODEL = 'face_detector/res10_300x300_ssd_iter_140000.caffemodel'


  File "pts_tools.py", line 8, in <module>
    import face_detector as fd
  File "/home/faust/LinuxCode/image_utility/face_detector.py", line 18, in <module>
    NET = dnn.readNetFromCaffe(PROTOTXT, MODEL)
cv2.error: OpenCV(3.4.3) /io/opencv/modules/dnn/src/caffe/caffe_io.cpp:1132: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "face_detector/res10_300x300_ssd_iter_140000.caffemodel" in function 'ReadProtoFromBinaryFile'

**Comment by faust690226** [comment]
版大,我後來去下面網站download了這兩個檔案,現在程式可以跑起來,
https://anonfile.com/W7rdG4d0b1/face_detector.rar
會跑出如圖1那樣一個小視窗, 然後每張圖掃描
但跑完後,為何我的ibug圖片沒有出現68個特徵點(如圖二)?
圖1：
![test](https://user-images.githubusercontent.com/39936662/46188643-e39cba00-c31c-11e8-8cea-82519019b488.jpeg)

圖2:
![indoor_001](https://user-images.githubusercontent.com/39936662/46188811-ee0b8380-c31d-11e8-9d39-e8ba1ec7d0ff.png)

**Comment by faust690226** [comment]
Hi 版主我成功了, 我發現要用extrace_face_from_ibug.py,且要把下面這段打開來,因為你註解掉,才能使用,你的文件可能要改一下...因為你文件上是寫用pts_tool那個檔案,且你的code也被註解掉了

        # Mark the result
        points_restored = []
        for point in points_normalized:
            points_restored.append([point[0] * TARGET_SIZE, point[1] * TARGET_SIZE])
        pt.draw_landmark_point(face_image, points_restored)

**Comment by xiaojunxuhaha** [comment]
@faust690226 请问一下 那个target_dir是在哪里呢？

**Comment by xiaojunxuhaha** [comment]
请问target_dir具体指的是那个路径呢

**Comment by faust690226** [comment]
Hi @xiaojunxuhaha 如下，可以參考這
extract face from ibug:It can extract face region for all pictures, and you need to set the following two parameters in this file.

DATA_DIR:The input source file path

TARGET_DIR:The target file path where you want to store.

**Comment by xiaojunxuhaha** [comment]
您好 谢谢您的回复 就是说target_dir一开始是不存在的 是你以后想用来存储 target file的地方是吗？因为我extract face from ibug一直报错 应该是图片读取不成功后来改了路径就输出All done! Total file: 0, invalid: 0, succeed: 0了 不太清楚哪里出了问题




------------------ 原始邮件 ------------------
发件人: "faust690226"<notifications@github.com>;
发送时间: 2019年4月11日(星期四) 上午9:48
收件人: "yinguobing/cnn-facial-landmark"<cnn-facial-landmark@noreply.github.com>;
抄送: "许晓君"<2314232838@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [yinguobing/cnn-facial-landmark] 請問一下, 運用PTS_Tool.py來畫出68個特徵點在圖片上出現問題 (#9)




Hi @xiaojunxuhaha 如下，可以參考這
 extract face from ibug:It can extract face region for all pictures, and you need to set the following two parameters in this file.
 
DATA_DIR:The input source file path
 
TARGET_DIR:The target file path where you want to store.

**Comment by xiaojunxuhaha** [comment]
@faust690226请问那个pts_tools，您的data_dir是 "/home/robin/Documents/landmark/dataset/“还是 "/home/robin/Documents/landmark/dataset/ibug“呢

**Comment by xiaojunxuhaha** [comment]
@faust690226您好 我的extract face from ibug跑通了但是生成的图片并没有关键点 您的有么 我的pts_tool文件的结果也是所有图片扫描后就没有了
Fitting failed!
Using minimal box.
opps! 394 566
就是这个结果， 我的extract face from ibug结果
New file saved:
C:/Users/Xuxiaojun/PycharmProjects/untitled15/223k/300vw\300vw-dataset-image_99.jpg
C:/Users/Xuxiaojun/PycharmProjects/untitled15/223k/300vw\300vw-dataset-image_99.json
All done! Total file: 135, invalid: 0, succeed: 135

Process finished with exit code 0
没有关键点。
如果您有时间请帮我看一下 谢谢您 打扰了
